m = input('Enter the no of m set elements')
m_values = input('Enter the elements')
m_newList = list(map(int, m_values.split()))
m_set = set(m_newList)
n = input('Enter the no of n set elements')
n_values = input('Enter the elements')
n_newList = list(map(int, n_values.split()))
n_set = set(n_newList)

print(type(m_set))